const assert=require('node:assert/strict');
const average=require('./average-display.cjs');
let state;
const pending=[];
const flush=t=>{pending.sort((a,b)=>a.t-b.t);while(pending.length && pending[0].t<=t){const e=pending.shift();send(e.msg,e.t);}};
const send=(msg,now)=>{const original=structuredClone(msg);const r=average(state,msg,now);assert.deepEqual(msg,original,'Raw input unchanged');state=r.state;return r.output;};
const row=(topic,extra={})=>({topic,label:topic.split('/').at(-1),raw:999,value:999,watts:999,seen:1,radioUnit:'dBm',...extra});
const rows=[row('TX-/1/FWDPWR',{power:true}),row('TX-/3/SWR',{radioUnit:'SWR'}),row('RAD/300/PACURRENT',{radioUnit:'Amps'}),row('TX-/2/REFPWR',{power:true}),row('RAD/8/PAFETQ1TEMP',{unit:'°C',radioUnit:'degF'}),row('RAD/7/PASTAT')];
const page=t=>{flush(t);return send({payload:{section:'pa',online:true,timestamp:t,rows}},t)[0].payload;};
const status=(tx,t,connected=true)=>{flush(t);return send({topic:'__radio_status',payload:{connected,at:t,activeSliceId:'7',fields:{'TX/RX':tx,'Mode':'TEST'}}},t);};
const sample=(topic,value,t,unit='dBm')=>pending.push({msg:{topic,payload:{value,unit}},t});
page(0);status('TX',0);
sample('TX-/1/FWDPWR',30,100);sample('TX-/1/FWDPWR',50,900);
sample('TX-/3/SWR',1.1,200,'SWR');sample('TX-/3/SWR',1.3,800,'SWR');
sample('RAD/300/PACURRENT',2,100,'Amps');sample('RAD/300/PACURRENT','4',500,'Amps');sample('RAD/300/PACURRENT',12,900,'Amps');
for(const invalid of [null,undefined,'',false,true,'broken',NaN,Infinity])sample('RAD/300/PACURRENT',invalid,950,'Amps');
sample('TX-/2/REFPWR',30,500);sample('TX-/2/REFPWR',50,600);
sample('RAD/8/PAFETQ1TEMP',32,500,'degF');sample('RAD/8/PAFETQ1TEMP',212,700,'degF');
sample('RAD/7/PASTAT',123,900,'bits');sample('SLC/7/LEVEL',-80,300);sample('SLC/7/LEVEL',-100,700);
let p=page(1000);
assert.equal(p.rows[0].average.raw,40);assert.equal(p.rows[0].average.watts,10,'Convert mean dBm, not mean Watts');
assert(Math.abs(p.rows[1].average.value-1.2)<1e-12);
assert.equal(p.rows[2].average.value,6,'All samples have equal weight');
assert.equal(p.rows[3].average.watts,10);assert.equal(p.rows[4].average.value,50);assert.equal(p.rows[5].average,null,'PASTAT not averaged');
assert.equal(p.rows[0].raw,999,'Original row still raw');assert.equal(p.radioStatus.fields['S-meter'],'-90 dBm');assert.equal(p.radioStatus.fields.Mode,'TEST');
sample('TX-/1/FWDPWR',60,1100);assert.equal(page(1200).rows[0].average.raw,40,'Publish means once per second');
p=page(2000);assert.equal(p.rows[0].average.raw,60,'Only rolling last second');
p=page(3000);assert.equal(p.rows[0].average.raw,60,'Empty window holds previous mean');
p=status('RX',3100)[0].payload;assert.equal(p.displayTx,false);assert.equal(p.rows[0].average,null);assert.equal(p.rows[1].average,null);
sample('TX-/1/FWDPWR',90,3200);assert.equal(state.windows['TX-/1/FWDPWR'],undefined,'RX samples rejected for display only');
status('TX',3500);sample('TX-/1/FWDPWR',30,3600);assert.equal(page(4000).rows[0].average,null,'Wait full new TX window');
sample('TX-/1/FWDPWR',40,4600);assert.equal(page(5000).rows[0].average.raw,40,'Previous TX cannot leak');
status('RX',5100,false);assert.equal(Object.keys(state.averages).length,0,'Disconnect resets display cache');
sample('EXT_WVF/958787990/FreeDV_SNR',4,5200,'');
flush(6000);
const ext=send({payload:{section:'external',rows:[row('EXT_WVF/0x3925F196/FreeDV_SNR')]}},6000)[3];
assert.equal(ext.payload.rows[0].average.value,4,'Hex topic alias preserved');
console.log('PASS: rolling arithmetic means, numeric filtering, rate limit, empty hold, dBm conversion order, unit conversion, TX cycle clearing, active LEVEL, discrete exclusion and raw immutability.');
