const assert = require('node:assert/strict');
const update = require('./live-state.cjs');
let s, now = 1000;
function send(msg) { const r=update(s,msg,now); s=r.state; return r; }
const status = () => send({status:{fill:'green',shape:'dot'}});
assert(Object.values(send({topic:'__radio_tick'}).snapshot.fields).every(v=>v==='--'));
assert.deepEqual(status().commands.map(c=>c.payload),['sub slice all','sub tx all']);
for (const request of ['sub slice all','sub tx all']) send({request,status_code:0,_radioEpoch:s.epoch,_radioRequestAt:now});
// Synthetic fixtures only; these are not observations or seeded station values.
const p={active:1,tx:0,index_letter:'Z',RF_frequency:14.123456,mode:'TEST',rxant:'RXTEST',filter_lo:-350,filter_hi:1850,lock:0,audio_mute:1,audio_level:27,nb:1,nr:0,anf:1,qsk:0,rit_on:1,rit_freq:-30,xit_on:0,xit_freq:70,dax:2};
send({topic:'slice/7',payload:p});
let f=send({topic:'slice/9',payload:{tx:1,txant:'TXTEST'}}).snapshot.fields;
assert.equal(f['Active slice'],'Z'); assert.equal(f.SPLIT,'ON'); assert.equal(f['TX/RX'],'--');
assert.equal(f['RX filter'],'2.2 kHz'); assert.equal(f['TX antenna'],'TXTEST');
assert.equal(f['DAX on'],'ON'); assert.equal(f['RIT offset'],'-30 Hz'); assert.equal(f.DSP,'--');
send({topic:'SLC/0/LEVEL',payload:{value:-77,unit:'dBm'}});
assert.equal(send({topic:'__radio_tick'}).snapshot.fields['S-meter'],'--');
f=send({topic:'SLC/7/LEVEL',payload:{value:-91.25,unit:'dBm'}}).snapshot.fields;
assert.equal(f['S-meter'],'-91.25 dBm');
f=send({topic:'slice/7',payload:{mode:'TEST2',dax:0,nb:0,nr:1,anf:0,filter_hi:450}}).snapshot.fields;
assert.equal(f.Frequency,'14.123456 MHz'); assert.equal(f.Mode,'TEST2'); assert.equal(f['DAX on'],'OFF'); assert.equal(f['RX filter'],'800 Hz');
assert.equal(send({topic:'interlock',payload:{state:'TRANSMITTING'}}).snapshot.fields['TX/RX'],'TX');
assert.equal(send({topic:'interlock',payload:{state:'READY'}}).snapshot.fields['TX/RX'],'RX');
assert.equal(send({topic:'interlock',payload:{state:'WAITING'}}).snapshot.fields['TX/RX'],'--');
send({topic:'slice/9',payload:{active:1}});
assert.equal(send({topic:'__radio_tick'}).snapshot.fields.Frequency,'--');
send({topic:'slice/7',payload:{active:0}});
f=send({topic:'slice/9',payload:{index_letter:'B',RF_frequency:7.1}}).snapshot.fields;
assert.equal(f.SPLIT,'OFF');assert.equal(f['S-meter'],'--'); assert.equal(f['Active slice'],'B');
send({topic:'slice/9',payload:'removed'});
assert.equal(send({topic:'__radio_tick'}).snapshot.fields.Frequency,'--');
send({topic:'slice/7',payload:{active:1}});
now += 16000; status();
assert.equal(send({topic:'__radio_tick'}).snapshot.fields['S-meter'],'--');
assert.equal(send({topic:'__radio_tick'}).commands.length,0);
f=send({topic:'connection/disconnected',payload:'disconnected'}).snapshot.fields;
assert(Object.values(f).every(v=>v==='--'));
assert.equal(status().commands.length,2);
assert.equal(send({topic:'__radio_tick'}).snapshot.fields.Mode,'--');
now += 13000;
assert(Object.values(send({topic:'__radio_tick'}).snapshot.fields).every(v=>v==='--'));
console.log('PASS: partial merge, selection/ambiguity/removal, exact active-slice meter, stale clearing, RX/TX, DSP unknown, reconnect and read-only command allowlist.');
